research_task:
  description: >
    Conduct a thorough research about {topic}.
    Make sure you find any interesting and relevant information about {topic}.
    Make sure your research is as deep as possible and as up to date as possible.
    Include some interesting github repositories and projects that are related to the topic.
    The current date is {current_date}.
  expected_output: >
    Cover one specific topic in {topic} and provide the most detailed and relevant information about it.
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
    Send a push notification with the title and the complete report content using the `PushoverNotificationTool`.
  agent: reporter
  context:
    - research_task
  output_file: outputs/report.md
